apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fire-prod

resources:
  - postgres-fire-user-sealed.yaml
  - database.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app: fire
