apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fire-prod

resources:
# Infrastructure
- ../../../../infrastructure/fire-postgres/overlays/prod
- ../../../../infrastructure/fire-ingress/overlays/prod

# Applications
- ../../../../applications/fire-backend/overlays/prod
