apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fire
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - fire.last-try.org
    secretName: fire-tls
  rules:
  - host: fire.last-try.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fire
            port:
              number: 3000
